### ISSUE TITLE
Processing TrieDateField with spark-solr

### ISSUE THREAD

**Issue by lujea** [lucidworks/spark-solr#107]
I have a solr index where there are few fields that are of type TrieDateField. I am able to create a dataframe that send a query to the index, however spark-solr does not seem to process the date fields. Here is the error message I get:

Caused by: java.lang.RuntimeException: java.io.IOException: --> http://10.10.X.X:31000/solr/ma_shard1_replica1/:Export fields must either be one of the following types: int,float,long,double,string
  at com.lucidworks.spark.query.TupleStreamIterator.hasNext(TupleStreamIterator.java:50)
  at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
  at org.apache.spark.scheduler.Task.run(Task.scala:86)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: --> http://10.10.X.X:31000/solr/ma_shard1_replica1/:Export fields must either be one of the following types: int,float,long,double,string
  at org.apache.solr.client.solrj.io.stream.SolrStream.read(SolrStream.java:228)
  at com.lucidworks.spark.query.TupleStreamIterator.fetchNextTuple(TupleStreamIterator.java:81)
  at com.lucidworks.spark.query.TupleStreamIterator.hasNext(TupleStreamIterator.java:46)

How can I query date fields without having to reindex all the date fields into integers ?

**Comment by kiranchitturi** [comment]
@lujea what version of spark-solr are you using ?

**Comment by lujea** [comment]
@kiranchitturi I am using spark-2.0.1-bin-hadoop2.6

**Comment by kiranchitturi** [comment]
The code is using /export handler and it looks like you have a solr version that does not support docValues for tdates. Better use the select handler with cursormarks. 

Add this to the options. (`rq` -> `/select`)

**Comment by kiranchitturi** [comment]
@lujea I was asking about spark-solr version? :)

**Comment by lujea** [comment]
No problem the solr index is 6.1.0 and spark-solr is spark-solr-3.0.0-alpha-shaded.jar

**Comment by kiranchitturi** [comment]
So, yeah. Add this to the options  and try again

`request_handler` -> `/select`

**Comment by lujea** [comment]
@kiranchitturi even using the /select request handler does not fix the issue. I still get the same error:
http://10.10.X.X:31000/solr/ma_shard1_replica1/:Export fields must either be one of the following types: int,float,long,double,string
  at com.lucidworks.spark.query.TupleStreamIterator.hasNext(TupleStreamIterator.java:50)
  at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)

**Comment by kiranchitturi** [comment]
can you share me your code snippet ?

**Comment by lujea** [comment]
import com.lucidworks.spark._
import org.apache.spark.SparkContext
import org.apache.spark.SparkConf
import org.apache.spark.rdd.PairRDDFunctions

val solr_collection_name = "ma"
val zk_connect_string = "10.10.X.X:32000/solr"

var options = Map("collection" -> "ma","zkhost" -> "10.10.X.X:32000/solr", "request_handler" -> "/selectt","splits" -> "true", "split_field" -> "id", "flatten_multivalued" -> "true", "batch_size" -> "50", "query" -> "documenttype:message", "fields" -> "id,msgid,documenttype,ownerstr,senderdomainstr,recipientdomainstr")
var solrData = spark.read.format("solr").options(options).load();
solrData.createOrReplaceTempView("maTable")
var sqlDF = spark.sql("SELECT ownerstr,senderdomainstr,startdate from maTable")
sqlDF.show()

**Comment by kiranchitturi** [comment]
there is a typo in your opts. It should be `/select`

**Comment by kiranchitturi** [comment]
`batch_size` is an index only param https://github.com/LucidWorks/spark-solr#index-parameters

**Comment by kiranchitturi** [comment]
`flatten_multivalued` is true by default. You don't need it as well

**Comment by lujea** [comment]
I have tried with this code. Essentially removing the "extra" parameters and also adding startdate in the initial query sent to solr

import com.lucidworks.spark._
import org.apache.spark.SparkContext
import org.apache.spark.SparkConf
import org.apache.spark.rdd.PairRDDFunctions

val solr_collection_name = "ma"
val zk_connect_string = "10.10.X.X:32000/solr"

var options = Map("collection" -> "ma","zkhost" -> "10.10.X.X:32000/solr", "request_handler" -> "/select","splits" -> "true", "split_field" -> "id", "query" -> "documenttype:message", "fields" -> "id,msgid,documenttype,ownerstr,senderdomainstr,recipientdomainstr,startdate")
var solrData = spark.read.format("solr").options(options).load();
solrData.createOrReplaceTempView("maTable")
var sqlDF = spark.sql("SELECT ownerstr,senderdomainstr,startdate from maTable")
sqlDF.show()

Unfortunately I still get the same problem. It keeps trying to use the /export handler:
Caused by: java.lang.RuntimeException: java.io.IOException: --> http://10.10.X.X:31000/solr/ma_shard1_replica1/:Export fields must either be one of the following types: int,float,long,double,string
  at com.lucidworks.spark.query.TupleStreamIterator.hasNext(TupleStreamIterator.java:50)
  at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
  at org.apache.spark.scheduler.Task.run(Task.scala:86)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

**Comment by kiranchitturi** [comment]
Thanks for trying. This is a bug with the version that you are using. Can you update to http://search.maven.org/#artifactdetails%7Ccom.lucidworks.spark%7Cspark-solr%7C3.0.0-alpha.2%7Cjar and try it again?

**Comment by kiranchitturi** [comment]
or the workaround with the version you are using is to put this in the options (`use_cursor_marks` -> `true`)

**Comment by lujea** [comment]
I'm going to try the workaround first :)

**Comment by lujea** [comment]
It works when using use_cursor_mark -> true. Thanks very much

**Comment by lujea** [comment]
@kiranchitturi thanks again, I will close the issue.

**Comment by kiranchitturi** [comment]
Sorry about the bug. It is fixed in the latest version :)

**Comment by lujea** [comment]
No problem, it should be fine with the workaround

**Comment by lujea** [comment]
By the way, the problem is still occurring with the spark-solr-3.0.0-alpha.2-shaded.jar when using the /export handler.
This are the options I used:
var options = Map("collection" -> "ma","zkhost" -> "10.10.X.X:32000/solr", "request_handler" -> "/export","splits" -> "true", "split_field" -> "id", "query" -> "documenttype:message", "fields" -> "id,msgid,documenttype,ownerstr,senderdomainstr,recipientdomainstr,startdate", "use_cursor_marks" -> "true")

http://10.10.X.X:31000/solr/ma_shard1_replica1/:Export fields must either be one of the following types: int,float,long,double,string
  at com.lucidworks.spark.query.TupleStreamIterator.hasNext(TupleStreamIterator.java:50)
  at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
  at org.apache.spark.scheduler.Task.run(Task.scala:86)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

Using "/select" is working on the other hand

**Comment by kiranchitturi** [comment]
yes, that is intended behavior. /export handler won't work with timestamp fields in 6.1.0.

The library does not gracefully switch behavior between different versions. Hence, the user has to add an explicit option. Good thing is that the /export handler works with timestamp fields from 6.2.1
